# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  bootDisk = "/dev/disk/by-uuid/C9FE-32FE";
  rootDisk = "/dev/disk/by-uuid/0bdba97c-e50f-4cc5-b7b0-d1048941541a";
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];


  ########################################
  # boot
  ########################################

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];

  boot.kernelModules = [ ]; # TODO: "kvm-intel"
  boot.extraModulePackages = [ ];


  ########################################
  # fileSystems
  ########################################

  fileSystems = {
    "/boot" = {
      device = bootDisk;
      fsType = "vfat";
    };

    "/" = {
      device = rootDisk;
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

    "/home" = {
      device = rootDisk;
      fsType = "btrfs";
      options = [ "subvol=root/home" "compress=zstd" ];
    };

    "/nix" = {
      device = rootDisk;
      fsType = "btrfs";
      options = [ "subvol=root/nix" "compress=zstd" "noatime" ];
    };

    "/swap" = {
      device = rootDisk;
      fsType = "btrfs";
      options = [ "subvol=root/swap" "noatime" ];
    };
  };

  swapDevices = [{ device = "/swap/swapfile"; }];

  services.btrfs.autoScrub = {
    enable = true;
    interval = "weekly";
  };


  ########################################
  # system
  ########################################

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Copy the NixOS configuration file and link it from the resulting system
  # (/run/current-system/configuration.nix). This is useful in case you
  # accidentally delete configuration.nix.
  # system.copySystemConfiguration = true;

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "23.11"; # Did you read the comment?
}
